#!/usr/bin/env python3
"""Create a simple PDF with Chinese text support.

Usage:
    python create_simple_pdf.py <output.pdf> <title> [content...]
    
Example:
    python create_simple_pdf.py report.pdf "AI 趋势报告" "2026 年发展趋势" "关键洞察"
"""

import sys
import os
from pathlib import Path

def register_chinese_font():
    """Register macOS system Chinese fonts"""
    try:
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont
        
        font_paths = [
            '/System/Library/Fonts/PingFang.ttc',
            '/System/Library/Fonts/STHeiti Light.ttc',
            '/System/Library/Fonts/STHeiti Medium.ttc',
            '/Library/Fonts/Arial Unicode.ttf',
        ]
        
        for font_path in font_paths:
            if os.path.exists(font_path):
                try:
                    if font_path.endswith('.ttc'):
                        font = TTFont('Chinese', font_path, subfontIndex=0)
                    else:
                        font = TTFont('Chinese', font_path)
                    
                    pdfmetrics.registerFont(font)
                    print(f"✅ Registered Chinese font: {font_path}")
                    return True
                except Exception as e:
                    print(f"⚠️ Failed to register {font_path}: {e}")
                    continue
        
        print("⚠️ No Chinese font available, using default")
        return False
    except ImportError:
        print("❌ reportlab not installed. Run: pip3 install reportlab")
        return False


def create_pdf(filename: str, title: str, content_lines: list[str] = None):
    """Create a simple PDF with optional Chinese text support.
    
    Args:
        filename: Output PDF filename
        title: Document title
        content_lines: Optional list of content lines
    """
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
    except ImportError:
        print("❌ reportlab not installed. Run: pip3 install reportlab")
        sys.exit(1)
    
    # Register Chinese font
    has_chinese_font = register_chinese_font()
    
    # Create PDF
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter
    
    y_position = height - 100
    
    # Title
    if has_chinese_font:
        c.setFont('Chinese', 24)
    else:
        c.setFont("Helvetica-Bold", 24)
    
    c.drawString(100, y_position, title)
    y_position -= 40
    
    # Content lines
    if content_lines:
        if has_chinese_font:
            c.setFont('Chinese', 14)
        else:
            c.setFont("Helvetica", 14)
        
        for line in content_lines:
            c.drawString(100, y_position, line)
            y_position -= 20
    
    # Footer
    if has_chinese_font:
        c.setFont('Chinese', 10)
    else:
        c.setFont("Helvetica", 10)
    
    c.drawString(100, 50, f"Generated by X-Agent PDF Skill")
    
    c.save()
    print(f"✅ PDF created: {filename}")
    print(f"   File size: {Path(filename).stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    
    output_file = sys.argv[1]
    title = sys.argv[2]
    content = sys.argv[3:] if len(sys.argv) > 3 else []
    
    create_pdf(output_file, title, content)
