"""Constants for Feishu channel behavior."""

FEISHU_CARD_MAX_BYTES = 30 * 1024
FEISHU_CARD_UPDATE_INTERVAL_SECONDS = 0.5
FEISHU_CARD_DEFAULT_TITLE = "X-Agent"
FEISHU_CARD_DEFAULT_STATUS = "正在生成"
FEISHU_CARD_DONE_STATUS = "已完成"
FEISHU_CARD_ERROR_STATUS = "处理失败"
FEISHU_CARD_TRUNCATED_SUFFIX = "\n\n_内容过长，已截断显示_"
